export const THIRD_PLACE_COMBINATIONS = {
  "EFGHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "F",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "DFGHIJKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "DEGHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "DEFHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "DEFGIJKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "DEFGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "DEFGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "DEFGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "DEFGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CFGHIJKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CEGHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "CEFHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CEFGIJKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CEFGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CEFGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CEFGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "CEFGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CDGHIJKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "CDFHIJKL": {
    third79: "C",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDFGIJKL": {
    third79: "C",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDFGHJKL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDFGHIKL": {
    third79: "C",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDFGHIJL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "CDFGHIJK": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CDEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "CDEGIJKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "CDEGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "CDEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "CDEGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "CDEGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "CDEFIJKL": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFHJKL": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFHIKL": {
    third79: "C",
    third85: "E",
    third81: "I",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFHIJL": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "CDEFHIJK": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CDEFGJKL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFGIKL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFGIJL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "CDEFGIJK": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CDEFGHKL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "CDEFGHJL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "CDEFGHJK": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "CDEFGHIL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "CDEFGHIK": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "CDEFGHIJ": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "BFGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BEGHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "B",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BEFHIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BEFGIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BEFGHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BEFGHIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "F",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BEFGHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "BEFGHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "H",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "BDGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BDFHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDFGIJKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDFGHJKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDFGHIKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDFGHIJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BDFGHIJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BDEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BDEGIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BDEGHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BDEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BDEGHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "BDEGHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "BDEFIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BDEFHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BDEFGJKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFGIJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BDEFGIJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BDEFGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BDEFGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "BDEFGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "BDEFGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BDEFGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BDEFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "BCGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BCFHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCFGIJKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCFGHJKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCFGHIKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCFGHIJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCFGHIJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BCEGIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BCEGHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "BCEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "BCEGHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "BCEGHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "BCEFIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCEFHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCEFGJKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFGIJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCEFGIJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCEFGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCEFGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "BCEFGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "BCEFGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCEFGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCEFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "BCDHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDGIJKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDGHJKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDGHIKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDGHIJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "BCDGHIJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "BCDFIJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFHJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFHIKL": {
    third79: "C",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFHIJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDFHIJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDFGJKL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFGIKL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFGIJL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDFGIJK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDFGHKL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDFGHJL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "BCDFGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "BCDFGHIL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDFGHIK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "BCDEIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "BCDEHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "BCDEGJKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEGIJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "BCDEGIJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "BCDEGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "BCDEGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "BCDEGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "E",
    third80: "K",
  },
  "BCDEGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "BCDEGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "H",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "BCDEGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "D",
    third87: "E",
    third80: "I",
  },
  "BCDEFJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDEFIKL": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDEFIJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDEFIJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDEFHKL": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDEFHJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "BCDEFHJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "BCDEFHIL": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDEFHIK": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDEFHIJ": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "BCDEFGKL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "BCDEFGJL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "BCDEFGJK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "BCDEFGIL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "BCDEFGIK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "E",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "BCDEFGIJ": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "J",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "BCDEFGHL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "BCDEFGHK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "BCDEFGHJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "J",
    third77: "F",
    third87: "D",
    third80: "E",
  },
  "BCDEFGHI": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "H",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "AFGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "AEGHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "A",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "AEFHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "AEFGIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "AEFGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "AEFGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "AEFGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "AEFGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ADGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ADFHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADFGIJKL": {
    third79: "I",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADFGHJKL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADFGHIKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADFGHIJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ADFGHIJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ADEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ADEGIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ADEGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ADEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ADEGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ADEGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ADEFIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFHJKL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFHIKL": {
    third79: "H",
    third85: "E",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFHIJL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ADEFHIJK": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ADEFGJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFGIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFGIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ADEFGIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ADEFGHKL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ADEFGHJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ADEFGHJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ADEFGHIL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ADEFGHIK": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ADEFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ACGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ACFHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACFGIJKL": {
    third79: "I",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACFGHJKL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACFGHIKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACFGHIJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACFGHIJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ACEGIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ACEGHJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ACEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ACEGHIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ACEGHIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ACEFIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFHJKL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFHIKL": {
    third79: "H",
    third85: "E",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFHIJL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACEFHIJK": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACEFGJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFGIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFGIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACEFGIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACEFGHKL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACEFGHJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ACEFGHJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ACEFGHIL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACEFGHIK": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACEFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ACDHIJKL": {
    third79: "H",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDGIJKL": {
    third79: "I",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDGHJKL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDGHIKL": {
    third79: "H",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDGHIJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDGHIJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDFIJKL": {
    third79: "C",
    third85: "J",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDFHJKL": {
    third79: "H",
    third85: "J",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDFHIKL": {
    third79: "H",
    third85: "F",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDFHIJL": {
    third79: "H",
    third85: "J",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDFHIJK": {
    third79: "H",
    third85: "J",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDFGJKL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDFGIKL": {
    third79: "C",
    third85: "G",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDFGIJL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACDFGIJK": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACDFGHKL": {
    third79: "H",
    third85: "G",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDFGHJL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "H",
  },
  "ACDFGHJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ACDFGHIL": {
    third79: "H",
    third85: "G",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDFGHIK": {
    third79: "H",
    third85: "G",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ACDEIJKL": {
    third79: "E",
    third85: "J",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEHJKL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEHIKL": {
    third79: "H",
    third85: "E",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEHIJL": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDEHIJK": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDEGJKL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEGIKL": {
    third79: "E",
    third85: "G",
    third81: "I",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEGIJL": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDEGIJK": {
    third79: "E",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDEGHKL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEGHJL": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ACDEGHJK": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "K",
  },
  "ACDEGHIL": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDEGHIK": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDEGHIJ": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "I",
  },
  "ACDEFJKL": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDEFIKL": {
    third79: "C",
    third85: "E",
    third81: "I",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDEFIJL": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACDEFIJK": {
    third79: "C",
    third85: "J",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACDEFHKL": {
    third79: "H",
    third85: "E",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ACDEFHJL": {
    third79: "H",
    third85: "J",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ACDEFHJK": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ACDEFHIL": {
    third79: "H",
    third85: "E",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ACDEFHIK": {
    third79: "H",
    third85: "E",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ACDEFHIJ": {
    third79: "H",
    third85: "J",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ACDEFGKL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ACDEFGJL": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ACDEFGJK": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ACDEFGIL": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ACDEFGIK": {
    third79: "C",
    third85: "G",
    third81: "E",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ACDEFGIJ": {
    third79: "C",
    third85: "G",
    third81: "J",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ACDEFGHL": {
    third79: "H",
    third85: "G",
    third81: "F",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ACDEFGHK": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ACDEFGHJ": {
    third79: "H",
    third85: "G",
    third81: "J",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "E",
  },
  "ACDEFGHI": {
    third79: "H",
    third85: "G",
    third81: "E",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ABGHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABFHIJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABFGIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABFGHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABFGHIKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABFGHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABFGHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABEHIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABEGIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABEGHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABEGHIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABEGHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "H",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABEGHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "H",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABEFIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABEFHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABEFHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABEFHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABEFHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABEFGJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABEFGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABEFGIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABEFGIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABEFGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABEFGHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "E",
  },
  "ABEFGHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "K",
  },
  "ABEFGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABEFGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABEFGHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "I",
  },
  "ABDHIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABDGIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABDGHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABDGHIKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABDGHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABDGHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABDFIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDFHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDFHIKL": {
    third79: "H",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDFHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABDFHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABDFGJKL": {
    third79: "F",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABDFGIKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDFGIJL": {
    third79: "F",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABDFGIJK": {
    third79: "F",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABDFGHKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDFGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "ABDFGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "J",
    third80: "K",
  },
  "ABDFGHIL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABDFGHIK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABDFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "J",
  },
  "ABDEIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABDEHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABDEHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABDEHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABDEHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABDEGJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABDEGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABDEGIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABDEGIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABDEGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABDEGHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "E",
  },
  "ABDEGHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "K",
  },
  "ABDEGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABDEGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABDEGHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "I",
  },
  "ABDEFJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDEFIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDEFIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABDEFIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABDEFHKL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDEFHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABDEFHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABDEFHIL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABDEFHIK": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABDEFHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABDEFGKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABDEFGJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "ABDEFGJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "J",
    third80: "K",
  },
  "ABDEFGIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABDEFGIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABDEFGIJ": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "J",
  },
  "ABDEFGHL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABDEFGHK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABDEFGHJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "J",
  },
  "ABDEFGHI": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABCHIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABCGIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABCGHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABCGHIKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABCGHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABCGHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABCFIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCFHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCFHIKL": {
    third79: "H",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCFHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCFHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCFGJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABCFGIKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCFGIJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABCFGIJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "F",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABCFGHKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCFGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "ABCFGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "J",
    third80: "K",
  },
  "ABCFGHIL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCFGHIK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCFGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "J",
  },
  "ABCEIJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "C",
    third87: "L",
    third80: "K",
  },
  "ABCEHJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABCEHIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABCEHIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABCEHIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABCEGJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABCEGIKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "A",
    third82: "I",
    third77: "C",
    third87: "L",
    third80: "K",
  },
  "ABCEGIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABCEGIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABCEGHKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "K",
  },
  "ABCEGHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "E",
  },
  "ABCEGHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "K",
  },
  "ABCEGHIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "L",
    third80: "I",
  },
  "ABCEGHIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "H",
    third87: "I",
    third80: "K",
  },
  "ABCEGHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "G",
    third87: "E",
    third80: "I",
  },
  "ABCEFJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCEFIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCEFIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCEFIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCEFHKL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCEFHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABCEFHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABCEFHIL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCEFHIK": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCEFHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABCEFGKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCEFGJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "ABCEFGJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "J",
    third80: "K",
  },
  "ABCEFGIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCEFGIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCEFGIJ": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "J",
  },
  "ABCEFGHL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABCEFGHK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABCEFGHJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "J",
  },
  "ABCEFGHI": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABCDIJKL": {
    third79: "I",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDHJKL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDHIKL": {
    third79: "H",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDHIJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDHIJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDGJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "K",
  },
  "ABCDGIKL": {
    third79: "I",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDGIJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "L",
    third80: "I",
  },
  "ABCDGIJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "G",
    third87: "I",
    third80: "K",
  },
  "ABCDGHKL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDGHJL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "J",
  },
  "ABCDGHJK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "J",
    third80: "K",
  },
  "ABCDGHIL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDGHIK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDGHIJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "J",
  },
  "ABCDFJKL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCDFIKL": {
    third79: "C",
    third85: "I",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCDFIJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCDFIJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCDFHKL": {
    third79: "H",
    third85: "F",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDFHJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "H",
  },
  "ABCDFHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ABCDFHIL": {
    third79: "H",
    third85: "F",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDFHIK": {
    third79: "H",
    third85: "F",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDFHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ABCDFGKL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCDFGJL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "J",
  },
  "ABCDFGJK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "J",
    third80: "K",
  },
  "ABCDFGIL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCDFGIK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCDFGIJ": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "J",
  },
  "ABCDFGHL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "H",
  },
  "ABCDFGHK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ABCDFGHJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "J",
  },
  "ABCDFGHI": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ABCDEJKL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDEIKL": {
    third79: "E",
    third85: "I",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDEIJL": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDEIJK": {
    third79: "E",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDEHKL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDEHJL": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ABCDEHJK": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "K",
  },
  "ABCDEHIL": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDEHIK": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDEHIJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "I",
  },
  "ABCDEGKL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "K",
  },
  "ABCDEGJL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "J",
  },
  "ABCDEGJK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "J",
    third80: "K",
  },
  "ABCDEGIL": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "I",
  },
  "ABCDEGIK": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "K",
  },
  "ABCDEGIJ": {
    third79: "E",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "I",
    third80: "J",
  },
  "ABCDEGHL": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ABCDEGHK": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "K",
  },
  "ABCDEGHJ": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "J",
  },
  "ABCDEGHI": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "E",
    third80: "I",
  },
  "ABCDEFKL": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "K",
  },
  "ABCDEFJL": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABCDEFJK": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABCDEFIL": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "I",
  },
  "ABCDEFIK": {
    third79: "C",
    third85: "E",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "I",
    third80: "K",
  },
  "ABCDEFIJ": {
    third79: "C",
    third85: "J",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABCDEFHL": {
    third79: "H",
    third85: "F",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "D",
    third87: "L",
    third80: "E",
  },
  "ABCDEFHK": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "K",
  },
  "ABCDEFHJ": {
    third79: "H",
    third85: "J",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "E",
  },
  "ABCDEFHI": {
    third79: "H",
    third85: "E",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "I",
  },
  "ABCDEFGL": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "L",
    third80: "E",
  },
  "ABCDEFGK": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "K",
  },
  "ABCDEFGJ": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "J",
  },
  "ABCDEFGI": {
    third79: "C",
    third85: "G",
    third81: "B",
    third74: "D",
    third82: "A",
    third77: "F",
    third87: "E",
    third80: "I",
  },
  "ABCDEFGH": {
    third79: "H",
    third85: "G",
    third81: "B",
    third74: "C",
    third82: "A",
    third77: "F",
    third87: "D",
    third80: "E",
  },
};